[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout
lib_deps = 
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/archive/master.zip
    https://github.com/bblanchon/ArduinoJson/archive/refs/tags/v6.19.4.zip