[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    blynkkk/Blynk @ ^1.3.2
    bblanchon/ArduinoJson @ ^7.0.4
    witnessmenow/UniversalTelegramBot @ ^1.3.0
    olikraus/U8g2 @ ^2.34.22
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14