[env:esp32dev]          ; (Hoặc tên board của bạn)
platform = espressif32
board = esp32dev
framework = arduino

; --- THÊM CÁC THƯ VIỆN CỦA BẠN VÀO ĐÂY ---
lib_deps =
    blynkkk/Blynk @ ^1.3.2
    bblanchon/ArduinoJson @ ^7.3.0