<<<<<<< HEAD
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

=======
>>>>>>> 19b3cf4ae0d69cf977ac0c59345b3860b25796a7
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

lib_deps =
    blynkkk/Blynk @ ^1.3.2
<<<<<<< HEAD
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    olikraus/U8g2 @ ^2.34.22
=======
    olikraus/U8g2 @ ^2.35.9
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4
    witnessmenow/UniversalTelegramBot @ ^1.3.0
>>>>>>> 19b3cf4ae0d69cf977ac0c59345b3860b25796a7
