#ifndef SECRETS_H
#define SECRETS_H
// --- BLYNK CONFIG ---
#define BLYNK_TEMPLATE_ID "TMPL6b5icRd1C"
#define BLYNK_TEMPLATE_NAME "ESP8266 BLYNK TELEGRAM"
#define BLYNK_AUTH_TOKEN "ew4gd5EqZvFSpFtBYwpxYkNFs_p5k-WM"

// --- CẤU HÌNH TELEGRAM ---
#define BOT_TOKEN "8719605408:AAG7XezTESD8N1lnwwsf-oYpdqAcLlQrcrU"
#define CHAT_ID "-5011054261"

#endif