[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps =
    bblanchon/ArduinoJson@^7.2.1
    adafruit/DHT sensor library@^1.4.6
    mhetesh/U8g2@^2.29.14
    adafruit/MQ2@^1.0.0
